ssh:
  host: ${SSH_HOST}
  private_key: ${PRIVATE_KEY}
  ssh_port: ${SSH_PORT}
  user: ${SSH_USER}
  password: ${SSH_PASSWORD}

spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          42Seoul:
            client-id: ${42SEOUL_CLIENT_ID}
            client-secret: ${42SEOUL_SECRET_ID}
            redirect-uri: ${42SEOUL_REDIRECT_URI}
            authorization-grant-type: authorization_code
        provider:
          42Seoul:
            authorization-uri: https://api.intra.42.fr/oauth/authorize
            token-uri: https://api.intra.42.fr/oauth/token
            user-info-uri: https://api.intra.42.fr/v2/me
            user-name-attribute: login
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: ${MAIL_SENDER} # 발신자(@ 앞의 아이디 부분만)
    password: ${MAIL_APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true # 사용자 인증 시도 여부(기본값: false)
          timeout: 5000 # Socket Read Timeout(ms) (기본값: 무한대)
          starttls:
            enable: true # StartTLS 활성화 여부 (기본값: false)

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG

jwt:
  secret:
    access-secret-key: ${JWT_ACCESS_SECRET}
    refresh-secret-key: ${JWT_REFRESH_SECRET}
  token:
      access-expiration: 3600000 # 1시간(1000(ms) * 60(m) * 60(h))
      access-header: Authorization
      refresh-expiration: 604800000 # 1주일(1000(ms) * 60(m) * 60(h) * 24(day) * 7(week)

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: true
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_ACCESS_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

application:
  bucket:
    name: ${BUCKET_NAME}



